### ISSUE TITLE
Logic Tree Editor - Add Object [Node]

### ISSUE THREAD

**Issue by ArkadiuszWernicki2000** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#13]
I was trying to add an object with this node, but despite the attempts, I couldn't do that.

**Comment by IzaZed** [comment]
Ah, indeed, this is because of the way the new UPBGE versions work with collections - I'll have to make the node work like the logic brick to add objects from a collection

thanks for reporting this :)

**Comment by IzaZed** [comment]
Working again! Make sure the object you want to add is hidden (eye icon in outliner)
