### ISSUE TITLE
Splashscreen

### ISSUE THREAD

**Issue by LP-ita** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#16]
Hi IzaZed, I took the liberty (in quarantine) to improve the splashscreen a little bit. if you like it, you are free to use it as you  want..  

![Splash_LogicNodes](https://user-images.githubusercontent.com/60321936/78371836-c9563300-75c8-11ea-9a3a-f5d3c92f5383.png)

**Comment by IzaZed** [comment]
That looks pretty cool :D Reminds me of the TrackMania Typography
Could you maybe send me the original editing file? :) I'd like to play around with the color a little, but it looks great :D thanks a lot man!
