### ISSUE TITLE
More Pop-Up windows

### ISSUE THREAD

**Issue by Shohrukh1999** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#17]
Hi, @IzaZed!
I think it would be better if, in the places of "**Action Name**", "**Path**" and ***similar places***, there was a pop-up window for selecting animations and a folder icon (button) for opening the explorer to select a file. 
Just like in Logic Bricks.
![IMG_20200411_142319](https://user-images.githubusercontent.com/46423713/79042113-65f28380-7c0e-11ea-9c78-c17051c733b6.png)
![IMG_20200411_140726](https://user-images.githubusercontent.com/46423713/79042157-c5e92a00-7c0e-11ea-9cac-aa5eb4d08358.png)
P.S. Thank you very much for such a great addon.

**Comment by IzaZed** [comment]
I did investigate this some time ago, but eventually came to a dead end because I couldn't figure out how to have the Items suggested by these pop-ups be contextual :/

Then again, I understand the whole thing quite a lot better now, so I'm gonna take a look at this 🙂

**Comment by IzaZed** [comment]
More Pointers! That's Done!
