### ISSUE TITLE
Filter properties

### ISSUE THREAD

**Issue by LP-ita** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#18]
Hi IzaZed, thanks for the update.
There's a lot of nodes now. Without a little bit of documentation, things are starting to get complicated... :-)

The property filter doesn't show integers. 

![Properties](https://user-images.githubusercontent.com/60321936/79042338-29fff400-7bf7-11ea-997f-95326345c45b.jpg)

**Comment by IzaZed** [comment]
Argh, darn it, I NEEEED to get myself to finish those docs! Such a dry piece of work ^^ I'll see what I can do!

Shooty, that's gotta have to do with the "Show Hidden" box now, I'm on it
Thanks 🙂

**Comment by IzaZed** [comment]
Alright, I messed that up somehow 🤷‍♂️ it's working now, though 👍
