### ISSUE TITLE
Save Game

### ISSUE THREAD

**Issue by LP-ita** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#19]
The node "Save Game" does not save anything if there is one o more lights on the scene...
    
'energy': obj.energy,
AttributeError: 'KX_LightObject' object has no attribute 'energy'

**Comment by IzaZed** [comment]
Mmh, I see, that's a 2.8 issue, I'm on it :)

**Comment by youle31** [comment]
Hi, about that, KX_LightObject has not anymore API in 2.8+.

Light settings have to be tweaked with blenderObject.

kxlight = kxscene.objects["Light"]
lightData = kxlight.blenderObject.data

lightData.energy += 0.1

**Comment by IzaZed** [comment]
I think this is fixed, but I don't really know, feel free to re-open this.

**Comment by LP-ita** [comment]
Great! I'll have a look this evening. Thank you.

**Comment by LP-ita** [comment]
Yes, I can now confirm that objects are saved and loaded correctly, but for example changing colour or energy of lights is not saved...
