### ISSUE TITLE
Feature request gravity nodes

### ISSUE THREAD

**Issue by mushroomeo** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#20]
hi , jsut wanted to ask if could make set gravity not only to characters but to normal rigid body . was really confused first why it didnt work on rigid body since i didnt read correctly... : (

and wanted say super thanks for this work . its so super fun now UPBGE becouse of this : )

**Comment by IzaZed** [comment]
Shouldn't be too hard, actually, I'll check it out :)

**Comment by IzaZed** [comment]
Alright, sorry for taking so long, it's in there now :)
