### ISSUE TITLE
Camera FOV controll for fps games

### ISSUE THREAD

**Issue by divineniiquaye** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#23]
Hi am trying to make an fps test just learning upbge and I must say i love ur nodes
pls an fov control will be legit for fps games, gives ability to zoom.
therefore am looking forward to seeing it :).

**Comment by IzaZed** [comment]
Oh yeah, that slipped somehow :thinking: I'll see to it :slightly_smiling_face: 
It really makes me happy to see people using it :smiley:

**Comment by IzaZed** [comment]
Should be working in 0.9 🙂

**Comment by divineniiquaye** [comment]
oof big sorry, ive been busy with work, am more active on discord. and yh we share the same server
u shud proly create a server for this. and use the gitbot for commit it will be great since most of us dont open up the browser regularly, and hell yh visual programming is the future 😃, 👍
