### ISSUE TITLE
Color too dark

### ISSUE THREAD

**Issue by divineniiquaye** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#24]
Hi i like black but this 1 is too much pls consider making a color bool switch in addon pref to toggle
where there to use colors.
![image](https://user-images.githubusercontent.com/53147395/84592577-3e9a7b80-ae36-11ea-8d5c-58fd42487b52.png)
thanks u :).

**Comment by IzaZed** [comment]
Aye, didn't consider custom themes there... will do :+1:

**Comment by IzaZed** [comment]
There's now a toggle for that :)
It only works for newly added nodes, so already added nodes won't change their color
