### ISSUE TITLE
Game Speed

### ISSUE THREAD

**Issue by divineniiquaye** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#26]
Hi there will be nice to control game speed like slow down and speedups
for like archer games where the game slows down when a player draws arow.
![image](https://user-images.githubusercontent.com/53147395/84597227-1a4c9800-ae52-11ea-9b64-bfbd7a52afa0.png)
this feature cannot be accessed by the logic nodes
will be fun if its available 👍

**Comment by IzaZed** [comment]
Will check it, I don't know if the feature is functional in UPBGE 0.3 in general though :thinking: Needs testing I guess

**Comment by IzaZed** [comment]
Cn be set now via Scene -> Set Timescale 👍
