### ISSUE TITLE
add paetron link to readme

### ISSUE THREAD

**Issue by BluePrintRandom** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#27]
add paetron link to readme to have people donate to you for this*

**Comment by BluePrintRandom** [comment]
https://www.patreon.com/iza_zed_upbge_toolkits/posts

**Comment by IzaZed** [comment]
Thanks for the suggestion 🙂 
I added it to the ReadMe and a button to Github and Patreon in the AddonPreferences
