### ISSUE TITLE
After exporting runtime the nodes don't work 

### ISSUE THREAD

**Issue by ElioOnPC** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#28]
after i export a run time test with a simple node init --> rove object it wont run the nodes

**Comment by ElioOnPC** [comment]
am getting this error C:\Users\admind>C:\Users\admind\Documents\Release\test\teste.exe
BLT_lang_init: 'locale' data path for translations not found, continuing
found bundled python: C:\Users\admind\Documents\Release\test\2.90\python
Exception in module register(): C:\Users\admind\Documents\Release\test\2.90\scripts\addons\cycles\__init__.py
Traceback (most recent call last):
  File "C:\Users\admind\Documents\Release\test\2.90\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\admind\Documents\Release\test\2.90\scripts\addons\cycles\__init__.py", line 124, in register
    from . import properties
  File "C:\Users\admind\Documents\Release\test\2.90\scripts\addons\cycles\properties.py", line 34, in <module>
    import _cycles
ModuleNotFoundError: No module named '_cycles'
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GTX 1070/PCIe/SSE2
GL_VERSION: 4.5.0 NVIDIA 446.14
GL_SHADING_LANGUAGE_VERSION: 4.50 NVIDIA
Supported Extensions...
 GL_ARB_shader_objects supported?       yes.
 GL_ARB_geometry_shader4 supported?     yes.
 GL_ARB_vertex_shader supported?        yes.
 ----------Details----------
  Max uniform components.4096
  Max varying floats.124
  Max vertex texture units.32
  Max vertex attribs.16
  Max combined texture units.192

 GL_ARB_fragment_shader supported?      yes.
 ----------Details----------
  Max uniform components.4096

 GL_ARB_texture_cube_map supported?     yes.
 ----------Details----------
  Max cubemap size.32768

 GL_ARB_multitexture supported?         yes.
 ----------Details----------
  Max texture units available.  4

 GL_ARB_texture_env_combine supported?  yes.
 GL_ARB_draw_instanced supported?  yes.
Error: NodeTree_NL_PY(Cube), Python module can't be imported
ModuleNotFoundError: No module named 'bgelogic'
Error: totblock: 122

**Comment by IzaZed** [comment]
Did you save the .exe in the same location where the blend file is?
Otherwise you might need to locate your file and copy the bgelogic folder to your executable, that should work.

This is because the addon generates that bgelogic folder and stores the necessary code in there, so whenever you want to have a nodetree perform you need that folder in the directory you are executing your file from

Let me know if that works :)

**Comment by ElioOnPC** [comment]
That fixed it thanks for the help look foreword for new release :)
