### ISSUE TITLE
Object Follow Mouse

### ISSUE THREAD

**Issue by ShaunKulesa** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#38]
Hello, I know how to code this but i'm trying to help a beginner make an object follow the mouse cursor with the logic nodes.
I attempted it this way but i was not successful.
![image](https://user-images.githubusercontent.com/69469909/101992098-b1cb6000-3ca8-11eb-8b5a-61a8d82666b7.png)
what would i need to make an object follow the mouse cursor?

**Comment by IzaZed** [comment]
Could this be what you want? The Depth would be the distance from the camera

![maybethis](https://user-images.githubusercontent.com/32898133/102001179-30e38700-3cef-11eb-91ea-f22c2ce79eef.PNG)

Alternatively, you could do this:

![orthis](https://user-images.githubusercontent.com/32898133/102001140-d77b5800-3cee-11eb-8a4b-8d28984dc4dd.PNG)

But that requires the object along which the main object can be positioned to have a property for which the raycast can look and the main object to be set to "No Collision"

I want to get a proper documentation up when the nodes work as intended, I think that should be sometime soon 🙂

**Comment by IzaZed** [comment]
Oopsi! Relace that "On Update" with a "Mouse Moved" condition, it's easier on the system

**Comment by IzaZed** [comment]
![ohwell](https://user-images.githubusercontent.com/32898133/102010051-c0168c00-3d3b-11eb-9f76-663ca5854892.PNG)

I had the file open and tabbed to it, then I got invested... here's a setup that mixes both of the former approaches

**Comment by ShaunKulesa** [comment]
I will now try thank you!

**Comment by ShaunKulesa** [comment]
In the your first comment the second example is very stuttery with a cube, will his be faster with an empty? Because its going to be used for spawning objects an an emptys position.

**Comment by ShaunKulesa** [comment]
Yeah with a empty it stutters abit.

**Comment by IzaZed** [comment]
It should be fast, do you get any error messages?

I set up a discord server for these types of questions because I get notified way faster, should we try to find a solution there? 🙂

**Comment by ShaunKulesa** [comment]
sure
