### ISSUE TITLE
set animation frame (node) didnt work 

### ISSUE THREAD

**Issue by mhreez** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#40]
set animation frame  (node) didnt work

https://user-images.githubusercontent.com/55386433/104091379-b3774c00-5285-11eb-9b54-0d1901071553.mp4

I am eorking on 
UPBGE-EEVEE-Win64-2021-01-07

**Comment by IzaZed** [comment]
Does the console print out any errors? 🤔 
I tried it just now, my basic health bar animation worked fine...

**Comment by mhreez** [comment]
no I cant see any error

still dosent work 

File
[TRY.zip](https://github.com/IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes/files/5791457/TRY.zip)

**Comment by IzaZed** [comment]
Indeed, there's been some changes in the last version I guess, I can confirm the issue

I'll see what I can do 👍

**Comment by IzaZed** [comment]
Alright, I tried to update the Set Frame Node, it should work now
Careful: When Initiating an action using the Set Frame Node, the node now checks for the first and last keyed frame automatically, so you can't set the frame range (Use Play Animation for that first)

Also, this setup does the same thing yours does and uses less processing power 🙂 
![smaller](https://user-images.githubusercontent.com/32898133/104125184-78dce480-5355-11eb-8b8a-bb7b0d575b88.PNG)

**Comment by mhreez** [comment]
woooow thank you man keep going

**Comment by mhreez** [comment]
thank you 

but
I used last version 11/1/2021
didnt work to 


[TRY.zip](https://github.com/IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes/files/5797654/TRY.zip)

**Comment by IzaZed** [comment]
I can't seem to reproduce it now, the file is working for me out of the box 🙁

**Comment by IzaZed** [comment]
Can you maybe give me additional info?

**Comment by IzaZed** [comment]
I think after all I found the issue here, I'm closing this now as I think that I put a fix in place

**Comment by mhreez** [comment]
thank you it is warking now
