### ISSUE TITLE
Node 0.9.6 Not Working in UPBGE 0.2.5 !?

### ISSUE THREAD

**Issue by Mohamedallouha** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#41]
hello
is 0.9.6 version working on EEVEE or 2.79 ??
it didnt work in UPBGE0.2.5 (2.79) (Latest Realese)
thank you :)

**Comment by IzaZed** [comment]
Hi, the current versions are only for 0.3.0, once I am happy with all of the nodes and a full release is available for it, I'll adapt it for 0.2.5 again :)

**Comment by Mohamedallouha** [comment]
❤❤❤
