### ISSUE TITLE
Collision Node Problem

### ISSUE THREAD

**Issue by Mohamedallouha** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#42]
Collision Node has some problems
the following image can expalain ..better than i ever can (weak in english 😅😅)
![false](https://user-images.githubusercontent.com/63161724/107124164-6c8b6f00-68a2-11eb-8e48-32d933b988e7.png)

**Comment by IzaZed** [comment]
What exactly is your setup?

The Collision node only reroutes collision callbacks, so it should be linked directly to object collisions 🤔
