### ISSUE TITLE
Help & Documentation links

### ISSUE THREAD

**Issue by lordloki** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#47]
in Logic nodes under "Help & Documentation" tab there are 3 links:

- Blender/BGE API
- UPBGE Manual
- Logic Nodes wiki

The 2 first are outdated. The current links are:
- https://upbge.org/api
- https://upbge.org/manual

With respect to the third one, I'm starting to include Logic Nodes documentation in the UPBGE Manual based in your documentation (and complete it where i can).

**Comment by IzaZed** [comment]
Oh, I see, I'm updating them now, thanks for reporting this

That would be great! I will add to the manual too, it'll be nice to have all the info together in one place 😃
