### ISSUE TITLE
Logic Tree

### ISSUE THREAD

**Issue by LP-ita** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#48]
Hi Iza I've tried deactivating a few nodes (logic-eaters) but it seems that node Stop Logic Tree and Start Logic Tree are not working... if you can check it out... thanks.

**Comment by IzaZed** [comment]
Ah that might be
I changed some things there recently, I'll look into it today

**Comment by IzaZed** [comment]
Should be fixed here: 91d3edbc5e07fe2bb4775b8ee539578915ef8cb5

**Comment by LP-ita** [comment]
Number One!!!
