### ISSUE TITLE
Sound nodes

### ISSUE THREAD

**Issue by LP-ita** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#49]
Hey Iza_Zed is it correct that the sound node activates the "done" socket instantly and not at the end of the sound or n-time sounds execution?

**Comment by IzaZed** [comment]
Yeah that's true, that socket just confirms that the node was executed
I'll add a "On Finish" socket to sound nodes

**Comment by LP-ita** [comment]
Great!

**Comment by IzaZed** [comment]
Implemented :+1:
