### ISSUE TITLE
Random Integer Node

### ISSUE THREAD

**Issue by LP-ita** [IzaZed/Uchronian-Logic-UPBGE-Logic-Nodes#8]
Hi IzaZed, I'm L_P from BlenderArtist.
Testing this node I found it returns two values instead of one. Not a big issue, but little bit annoying. : ) 
Ciao.

![RandomInteger](https://user-images.githubusercontent.com/60321936/73138956-b3783f00-4068-11ea-9578-514f59620246.png)

**Comment by IzaZed** [comment]
Hi!
I tested it and I can't seem to reproduce this, have you maybe attached the tree to two objects at the same time? That's how I just got it to spit out two numbers at once

Note that when applying a tree, it gets applied to ALL selected objects :)

**Comment by LP-ita** [comment]
Yes, I tried it again with a new scene and the problem didn't come up. Probably my incorrect setting...
